#!/usr/bin/env node
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const src = resolve(root, "..", ".claude", "skills", "deployik-howto");
const dest = resolve(root, "src", "knowledge", "recipes");
const generated = resolve(root, "src", "knowledge", "recipes.generated.ts");

if (!existsSync(src)) {
  console.error(`[copy-recipes] source missing: ${src}`);
  process.exit(1);
}

mkdirSync(dest, { recursive: true });

const files = readdirSync(src, { withFileTypes: true })
  .filter((e) => e.isFile() && e.name.endsWith(".md"))
  .map((e) => e.name)
  .sort();

if (files.length === 0) {
  console.error(`[copy-recipes] no markdown files in ${src}`);
  process.exit(1);
}

const entries = [];
for (const file of files) {
  cpSync(join(src, file), join(dest, file));
  const content = readFileSync(join(src, file), "utf8");
  entries.push({ file, content });
}

const tsLines = [
  "// AUTO-GENERATED by scripts/copy-recipes.mjs. Do not edit by hand.",
  "// Source: ../../.claude/skills/deployik-howto/",
  "",
  "export interface RecipeFile {",
  "  file: string;",
  "  content: string;",
  "}",
  "",
  "export const RECIPE_FILES: RecipeFile[] = [",
];
for (const { file, content } of entries) {
  tsLines.push(`  {`);
  tsLines.push(`    file: ${JSON.stringify(file)},`);
  tsLines.push(`    content: ${JSON.stringify(content)},`);
  tsLines.push(`  },`);
}
tsLines.push("];");
tsLines.push("");

writeFileSync(generated, tsLines.join("\n"), "utf8");

// Bake the package.json version into a TS module so server.ts can serve the
// real version in McpServer({version}) instead of a hardcoded string.
const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
const versionFile = resolve(root, "src", "version.ts");
const versionContent = `// AUTO-GENERATED by scripts/copy-recipes.mjs from ../package.json. Do not edit by hand.\nexport const VERSION = ${JSON.stringify(pkg.version)};\n`;
writeFileSync(versionFile, versionContent, "utf8");

console.log(`[copy-recipes] copied ${files.length} recipe files; baked version ${pkg.version}`);
