#!/usr/bin/env node
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const src = resolve(root, "..", ".claude", "skills", "deployik-howto");
const dest = resolve(root, "src", "knowledge", "recipes");
const generated = resolve(root, "src", "knowledge", "recipes.generated.ts");

if (!existsSync(src)) {
  console.error(`[copy-recipes] source missing: ${src}`);
  process.exit(1);
}

mkdirSync(dest, { recursive: true });

const skillFiles = listFiles(src);
const recipeFiles = skillFiles.filter((file) => file.endsWith(".md"));

if (recipeFiles.length === 0) {
  console.error(`[copy-recipes] no markdown files in ${src}`);
  process.exit(1);
}

const recipeEntries = [];
for (const file of recipeFiles) {
  const content = readFileSync(join(src, file), "utf8");
  cpSync(join(src, file), join(dest, file));
  recipeEntries.push({ file, content });
}

const skillEntries = [];
for (const file of skillFiles) {
  const fullPath = join(src, file);
  const mode = statSync(fullPath).mode & 0o777;
  skillEntries.push({
    file,
    content: readFileSync(fullPath, "utf8"),
    executable: (mode & 0o111) !== 0,
  });
}

const tsLines = [
  "// AUTO-GENERATED by scripts/copy-recipes.mjs. Do not edit by hand.",
  "// Source: ../../.claude/skills/deployik-howto/",
  "",
  "export interface RecipeFile {",
  "  file: string;",
  "  content: string;",
  "}",
  "",
  "export interface SkillFile extends RecipeFile {",
  "  executable?: boolean;",
  "}",
  "",
  "export const RECIPE_FILES: RecipeFile[] = [",
];
for (const { file, content } of recipeEntries) {
  tsLines.push(`  {`);
  tsLines.push(`    file: ${JSON.stringify(file)},`);
  tsLines.push(`    content: ${JSON.stringify(content)},`);
  tsLines.push(`  },`);
}
tsLines.push("];");
tsLines.push("");
tsLines.push("export const SKILL_FILES: SkillFile[] = [");
for (const { file, content, executable } of skillEntries) {
  tsLines.push(`  {`);
  tsLines.push(`    file: ${JSON.stringify(file)},`);
  tsLines.push(`    content: ${JSON.stringify(content)},`);
  if (executable) tsLines.push(`    executable: true,`);
  tsLines.push(`  },`);
}
tsLines.push("];");
tsLines.push("");

writeFileSync(generated, tsLines.join("\n"), "utf8");

// Bake the package.json version into a TS module so server.ts can serve the
// real version in McpServer({version}) instead of a hardcoded string.
const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
const versionFile = resolve(root, "src", "version.ts");
const versionContent = `// AUTO-GENERATED by scripts/copy-recipes.mjs from ../package.json. Do not edit by hand.\nexport const VERSION = ${JSON.stringify(pkg.version)};\n`;
writeFileSync(versionFile, versionContent, "utf8");

console.log(`[copy-recipes] copied ${recipeFiles.length} recipe files and bundled ${skillFiles.length} skill files; baked version ${pkg.version}`);

function listFiles(dir, prefix = "") {
  const entries = readdirSync(dir, { withFileTypes: true })
    .filter((entry) => !entry.name.startsWith("."))
    .sort((a, b) => a.name.localeCompare(b.name));
  const files = [];
  for (const entry of entries) {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...listFiles(fullPath, relative));
    } else if (entry.isFile()) {
      files.push(relative);
    }
  }
  return files;
}
